---
- name: ensure vim-plug dir
  file:
    path: "{{ vim_plug_dir }}"
    state: directory

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_plug_path }}"
