---
- name: ensure dir
  ansible.builtin.file:
    state: directory
    path: "{{ tools_dir + '/microsoft/powershell/7' }}"
    mode: 0755
  become: true

- name: download and unzip
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ pwsh_archive_url }}"
    dest: "{{ tools_dir + '/microsoft/powershell/7' }}"
  become: true

- name: Set executable
  ansible.builtin.file:
    path: "{{ tools_dir + '/microsoft/powershell/7/pwsh' }}"
    mode: 0755
    state: file
  become: true

- name: add sym-link
  ansible.builtin.file:
    path: /usr/bin/pwsh
    src: "{{ tools_dir + '/microsoft/powershell/7/pwsh' }}"
    state: link
  become: true
