---
- name: check installed
  shell:
    cmd: pwsh -version
    warn: false
  register: version
  ignore_errors: true


- name: 'Install powershell debian 11'
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11" and version.failed
  include_tasks: deb_11.yml

- name: 'Install powershell debian <11'
  when: ansible_distribution == "Debian" and ansible_distribution_major_version != "11"
  apt:
    name: powershell
    present: true
    update_cache: true
  become: true
