---
- name: download installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rust-init
    mode: 0755

- name: install
  shell: /tmp/rust-init -y

- name: remove installer
  file:
    path: /tmp/rust-init
    state: absent
