---
- name: ensure prereqs
  apt:
    name:
      - pkg-config
      - libncursesw5-dev
      - libreadline-dev
      - unzip
    update_cache: true
    state: present
  become: true

- name: download and unzip
  unarchive:
    dest: /tmp/
    remote_src: true
    src: https://github.com/jarun/nnn/archive/refs/tags/v4.5.zip

- name: make
  make:
    chdir: /tmp/nnn-4.5
    params:
      0_GITSTATUS: 1
      0_NERD: 1

- name: install
  copy:
    remote_src: true
    src: /tmp/nnn-4.5/nnn
    dest: "{{ tools_dir + '/nnn/' }}"
    mode: 755
  become: true

- name: add sym-link to /usr/bin
  file:
    path: /usr/bin/nnn
    src: "{{ tools_dir + '/nnn/nnn' }}"
    state: link
  become: true
