---
- name: ensure python3, pip and virtualenv are installed
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - virtualenv
    state: present
    update_cache: true
  become: true

- name: install
  ansible.builtin.pip:
    name: az-cli
    state: present
    virtualenv: "{{ venv_dir + '/az-cli' }}"
