# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = 'kalitest'
HOSTNAME = 'kali-hostname'
BOXNAME = HOSTNAME
CPUS = 2
MEMORY = 2048

Vagrant.configure('2') do |config|
  config.vm.box = BOX
  config.vm.hostname = HOSTNAME

  config.vm.provider 'parallels' do |prl|
    prl.name = BOXNAME
    prl.cpus = CPUS
    prl.memory = MEMORY
    prl.customize ['set', :id,
                   '--sync-host-printers', 'off',
                   '--auto-share-camera', 'off',
                   '--auto-share-bluetooth', 'off']
    prl.update_guest_tools = true
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = '../../ansible/main.yml'
    ansible.groups = {
      'full_box' => ['default'],
      'parallels' => ['default'],
      'utils' => ['default'],
      'custom' => ['default'],
      'security' => ['default'],
      'cloud' => ['default']
    }
    ansible.host_vars = {
      'default' => {
        'gui' => 'xfce' # xfce, gnome, kde, mate, i3
      }
    }
    ansible.vault_password_file = '../../secrets/pass'
    # ansible.verbose = '-vvv'
  end
end
