---
- name: install linux headers
  ansible.builtin.apt:
    name: linux-headers-{{ ansible_kernel }}
    state: present
  become: true

- name: mount installer
  ansible.posix.mount:
    src: /home/vagrant/prl-tools-lin-arm.iso
    path: /tmp/parallels
    state: mounted
    fstype: iso9660
  become: true

- name: get version
  ansible.builtin.slurp:
    src: /tmp/parallels/version
  register: pt_version
  become: true

- name: print version
  ansible.builtin.debug:
    msg: "Parallels Tools Version {{ pt_version.content | b64decode }}"
  become: true

- name: install
  ansible.builtin.command:
    cmd: /tmp/parallels/install --install-unattended-with-deps
  register: install
  changed_when: install.rc == 0
  become: true

- name: unmount installer
  ansible.posix.mount:
    src: /home/vagrant/prl-tools-lin-arm.iso
    path: /tmp/parallels
    state: absent
    fstype: iso9660
  become: true


- name: remove iso
  ansible.builtin.file:
    path: /home/vagrant/prl-tools-lin-arm.iso
    state: absent
