---
- name: ensure dir
  ansible.builtin.file:
    path: "{{ rust_lsp_dir }}"
    state: directory
    mode: 0755
  become: true


- name: download
  ansible.builtin.get_url:
    url: "{{ rust_lsp_url }}"
    dest: "{{ rust_lsp_dir + '/rust-analyzer.gz' }}"
    mode: 0644
  become: true

- name: unzip
  ansible.builtin.command:
    cmd: "{{ 'gunzip -q ' + rust_lsp_dir + '/rust-analyzer.gz' }}"
  become: true
  register: unzip
  changed_when: unzip.rc == 0

- name: set permissions
  ansible.builtin.file:
    path: "{{ rust_lsp_dir + '/rust-analyzer' }}"
    state: file
    mode: 0755
  become: true

- name: add sym-link to /usr/bin
  ansible.builtin.file:
    path: /usr/bin/rust-analyzer
    src: "{{ rust_lsp_dir + '/rust-analyzer' }}"
    state: link
  become: true
